### ISSUE TITLE
enhancement: Dockerize application

### ISSUE THREAD

**Issue by identor** [trenchdevs/trenchdevs#23]
Checklist:

- [x] Address blocker: https://github.com/trenchdevs/trenchdevs/issues/31
- [x] Be able to run app without installing runtime (php), and database
- [x] and also to be run app in Docker runtime, given image
- [x] To publish, and easily run app
  - [x] Create docker hub organization
  - [x] Push initial image, latest working version

**Comment by identor** [comment]
@christopheredrian , created docker hub organization I can add you here: https://hub.docker.com/orgs/trenchdevs

**Comment by christopheredrian** [comment]
@identor Thank you! Newbie here on docker images, sent you my id via mail
